[project]
name = "simple-player"
version = "1.0.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mutagen>=1.47.0",
    "pygame>=2.6.1",
    "pyside6>=6.10.1",
]
